apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: timeservers.timeserver.example.com
spec:
  group: timeserver.example.com
  names:
    kind: TimeServer
    listKind: TimeServerList
    plural: timeservers
    singular: timeserver
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: TimeServer is the Schema for the timeservers API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: TimeServerSpec defines the desired state of TimeServer
          properties:
            size:
              description: Size is the size of the timeserver deployment
              format: int32
              type: integer
          required:
          - size
          type: object
        status:
          description: TimeServerStatus defines the observed state of TimeServer
          properties:
            nodes:
              description: Nodes are the names of the timeserver pods
              items:
                type: string
              type: array
          required:
          - nodes
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
