apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-go-server
  labels:
    app: serverapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: serverapp
  template:
    metadata:
      labels:
        app: serverapp
    spec:
      containers:
      - name: serverapp
        image: quay.io/sdhaliwa/rampup-unix-time-server-app
        ports:
        - containerPort: 8080        