apiVersion: v1
kind: Service
metadata:
  name: app-service
  labels:
    app: serverapp
spec: 
  selector:
    app: http-go-server
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    name: goserver
